# Generated by Django 5.0.7 on 2024-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_frequency_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtask",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("monthly", "Monthly"),
                    ("bimonthly", "Bimonthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Frequency",
        ),
    ]
