# Generated by Django 5.0.7 on 2024-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_recurringtask_frequency_delete_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtask",
            name="day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recurringtask",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
            ),
        ),
    ]
